site_name: Linux Notes
site_url: https://nhattran02.github.io/my-notes

repo_name: nhattran02/my-notes
repo_url: https://github.com/nhattran02/my-notes

theme:
  name: material

  font:
    text: Inter
    code: JetBrains Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - content.tooltips
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

  language: en

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true

  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md

  - RZ/G2L SMARC:
      - g2l/000index.md
      - Boot modes & flash bootloader: g2l/001boot.md
      - Yocto BSP build: g2l/yocto.md
      - Kernel & Device Tree: g2l/kernel.md
      - Peripherals: g2l/peripherals.md
      - Cortex-M33 / remoteproc: g2l/cm33.md

  - RZ/V2N EVK:
      - v2n/index.md
      - Board setup: v2n/setup.md
      - Boot modes & flashing: v2n/boot.md
      - Yocto BSP build: v2n/yocto.md
      - DRP-AI development: v2n/drpai.md
      - Peripherals: v2n/peripherals.md

  
